# Nội dung
1. Vector
* Ký hiệu
* Elementwise operations
* Dot Product
* Inverse Vector
* Norm
2. Matrices
* Kích thước ma trận
* Scalar operations
* Elementwise operations
* Hadamard product
* Matrix mulitplication (nhân ma trận)
* Định thức - Determinants
3. Numpy
* Dot product
* Broadcasting
4. Linear Transformation
* Ma trận bậc

### **1. Vectors**
#### **1.1. Ký hiệu**
Có nhiều cách ký hiệu vector khác nhau, hình ảnh bên dưới miêu tả một số cách ký hiệu thường gặp

In [2]:
import numpy as np
v = np.array([1, 2, 3])

In [3]:
v

array([1, 2, 3])

##### **1.2 Elementwise operations**
Khi thực hiện các phép toán: cộng, trừ, nhân, chia,... các vector, Elementwise cho phép thực hiện các phép toán này từng vị trí tương ứng giữa các Vector.

Ví dụ: Phần tử thứ 1 của Vector A sẽ thực hiện cộng với phần tử thứ 1 của Vector B, phần tử thứ 2 của A sẽ thực hiện tương ứng với phần tử thứ 2 của B

In [4]:
import numpy as np
y = np.array([1, 2, 3])
x = np.array([2, 3, 4])
print(x + y)

[3 5 7]


In [5]:
print(x - y)
print(x / y)
print(2*x - 3*y)

[1 1 1]
[2.         1.5        1.33333333]
[ 1  0 -1]


#### **1.3 Phép nhân Vector**
Có 2 kiểu nhân Vector là: Dot Product và Hadamard Product
##### **1.3.1 Dot Product**
Tích của 2 vector sẽ là một vô hướng (scalar)

In [6]:
y = np.array([-1, 2, -3])
x = np.array([2, -3, 4])
np.dot(y, x)
# -1 *2 + 2 * (-3) + (-3) * 4

-20

In [7]:
y.dot(x)

-20

In [8]:
x.dot(y)

-20

In [9]:
x @ y

-20

Cosin giữa 2 vector

In [10]:
from numpy import dot
from numpy.linalg import norm

cos_sin = dot(x, y)/(norm(x)*norm(y))

In [11]:
cos_sin

-0.9925833339709303

#### **1.3.2 Hadamard Product**
Hadamard Product sẽ thực hiện phép nhân elementwise để tạo ra vector mới

In [12]:
y = np.array([1, 2, 3])
x = np.array([2, 3, 4])
y*x

array([ 2,  6, 12])

#### **1.4 Inverse Vector**

In [13]:
A = np.array([[2, 3],
              [4, 5]
])

In [14]:
A_inverse = np.linalg.inv(A)
A_inverse

array([[-2.5,  1.5],
       [ 2. , -1. ]])

In [15]:
A.dot(A_inverse)

array([[1., 0.],
       [0., 1.]])

#### **1.5 Norm**

In [16]:
# l1 norm of a vector
from numpy import array
from numpy.linalg import norm

a = array([-1, 100, -6, -11, 3])
print(a)
l1 = norm(a, 1)
print(l1)

[ -1 100  -6 -11   3]
121.0


In [17]:
# l2 norm  of a vector
a = array([
    [0, 3, 4]
])
print(a)
l2 = norm(a, 2)
print(l2)

[[0 3 4]]
5.0


### **2. Matrices**
Matrices (ma trận) là một lưới hình chữ nhật

##### **2.1 Kích thước ma trận**
Kích thước ma trận = `[số hàng x số cột]`

In [18]:
v = np.array([
    [2, 4],
    [5, -7],
    [12, 5]
])

In [19]:
v.shape

(3, 2)

In [20]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(a.shape)

(3, 3)


##### **2.2 Scalar operatoins**
Các phép toán liên quan đến scalar của Matrix có cách hoạt động  tương tự Vector

In [21]:
a = np.array([
    [1, 2],
    [3, 4]
])

a + 1

array([[2, 3],
       [4, 5]])

##### **2.3 Elementwise Operations**
Để có thể thực hiện phép Elementwist trên Matrix, các Matrix phải có **cùng kích thước** với nhau. Chúng ta sẽ thực hiện kết hợp các giá trị tương ứng với từng vị trí của các Matrix với nhau để tạo ra một Matrix mới

In [22]:
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [1, 2],
    [3, 4]
])

print("a + b: \n", a + b)

a + b: 
 [[2 4]
 [6 8]]


##### **2.4 Hadamard Product**
Matrix hadamard product sẽ thực hiện phép nhân elementwise

In [23]:
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [3, 4],
    [5, 6]
])

a * b

array([[ 3,  8],
       [15, 24]])

Trong python, chúng ta có thể sử dụng phép Hadamard giữa vector và matrix. Khi đó, Python sẽ sử dụng phương thức **Broadcasting** 

In [24]:
a = np.array([[2,3],
              [3,3]])

b = np.array([3,4])
# Uses python's multiply operator
a * b

array([[ 6, 12],
       [ 9, 12]])

##### **2.5 Matrix multiplication (nhân ma trận) - Dot product**
Cho hai ma trận $A(m\times n), B(n \times p)$, tích của hai ma trận được ký hiệu là $C = AB$, khi đó $C$ có kích thước $m \times p$.
*Chú ý*: Để nhân được hai ma trận, số cột của ma trận thứ nhất phải bằng số hàng của ma trận thứ hai.

Một số tính chất của ma trận:
* Phép nhân ma trận không có tính chất giao hoán
* Phép nhân ma trận có tính chất kết hợp: $ABC = (AB)C=A(BC)$
* Phép nhân ma trận có tính: $A(B+C)=AB+AC$
* Chuyển vị của một tích bằng tích chuyển vị theo thứ tự ngược lại: $(AB)^T=B^TA^T$

In [25]:
A = np.array([[1, 7], [2, 4]])
B = np.array([[3, 3], [5, 2]])

np.dot(A, B) 

array([[38, 17],
       [26, 14]])

In [26]:
A.dot(B)

array([[38, 17],
       [26, 14]])

In [27]:
np.dot(B, A)

array([[ 9, 33],
       [ 9, 43]])

##### **2.6 Ma trận chuyển vị**
Ma trận chuyển vị thường được ký hiệu bằng chữ $T$. Ví dụ chuyển vị của ma trận $M$ được ký hiệu $M^T$
Nếu $A^T=A$ thì ta nói $A$ là một ma trận đối xứng

In [28]:
a = np.array([[1, 2], 
              [3, 4]])

print(a.T)

[[1 3]
 [2 4]]


In [29]:
np.transpose(a)

array([[1, 3],
       [2, 4]])

##### **2.7 Định thức**

In [30]:
A = np.array([
              [1, -2, 4],
              [-5, 3, -1],
              [3, 4, 1]
])

np.linalg.det(A)

-113.00000000000003

### **3. Numpy**
#### **3.1 Dot Product**
Chúng ta sẽ sử dụng function ```np.dot``` (numpy.dot) để thực hiện phép Dot Product (nhân ma trận). Các bạn cần chú ý về kích thước của các phần tử khi thực hiện phép toán.

In [31]:
a = np.array([
    [1, 2]
])
print('a_shape: ', a.shape)

b= np.array([
    [3, 4],
    [5, 6]
])

print('b_shape: ', b.shape)

# Multiply
mm = np.dot(a, b)
print('mn: \n', mm)
print('mm_shape: ', mm.shape)

a_shape:  (1, 2)
b_shape:  (2, 2)
mn: 
 [[13 16]]
mm_shape:  (1, 2)


#### **3.2 Broadcasting**
Broadcasting cho phép thực thi các phép toán trên các mảng có kích thước khác nhau

Có thể Broadcasting nếu thỏa mãn các trường hợp sau:
* Mảng kích thước nhỏ hơn có thể được nối với `1` trong hình dạng của nó
* Kích thước của mỗi dimension output là kích thước tối đa trong input dimention
* Một input có thể được sử dụng trong tính toán nếu kích thước của nó trong một dimention cụ thể khớp với kích thước output hoặc giá trị của nó chính xác là `1`
* Nếu kích thước input là `1`, thì mục nhập dữ liệu đầu tiên được sử dụng để tính toán dọc theo dimension

Broadcast có thể được áp dụng cho các mảng nếu các quy tắc sau được thỏa mãn
* Tất cả các mảng đầu vào có cùng hình dạng
* Mảng có cùng số thứ nguyên và độ dài của mỗi thứ nguyên là độ dài chung hoặc `1`
* Mảng có kích thước ít hơn được nối với `1` trong hình dạng của nó

Tìm hiểu thêm: https://numpy.org/doc/stable/user/basics.broadcasting.html