### **NumPy là gì?**
Bạn có thể hiểu đơn giản: **Numpy** (Numeric Python) là thư viện cốt lõi cho tính toán khoa học trong Python. Nó cung cấp mối đối tuowngjd da chiều hiệu suất cao và các công cụ để làm việc với các mảng này

#### **ndarray**
ndarrays, mảng n chiều của kiểu dữ liệu đồng nhất, là kiểu dữ liệu cơ bản được sử dụng trong NumPy. Vì các mảng này cùng kiểu và có kích thước cố định khi tạo, chúng cung cấp độ linh hoạt kém hơn so với danh sách Python, nhưng về cơ bản có thể hiệu quả hơn về thời gian chạy và bộ nhớ. (Danh sách Python là mảng các con trỏ tới các đối tượng, thêm một lớp tham chiếu)

Số chiều chính là rank của mảng đó, shape của array là một tuple số nguyên đưa ra size của mảng theo mỗi chiều

Có thể tạo ndarray từ Python lists và truy cập vào các phần tử bằng dấu ngoặc vuông như sau

In [3]:
# Import library
import numpy as np


a = np.array([1, 2, 3]) # Creat a rank 1 array
print('type: ', type(a))
print('type a[0]: ', type(a[0]))
print('shape: ', a.shape)
print('a: ', a)
print(a[1])

b = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print('shape: ', b.shape) # Creat a rank 2 array
print(b[0, 0], b[0, 1], b[1, 0])

type:  <class 'numpy.ndarray'>
type a[0]:  <class 'numpy.int32'>
shape:  (3,)
a:  [1 2 3]
2
shape:  (2, 3)
1 2 4


Khi muốn tạo 1 mảng mới = 1 mảng cũ, ta nên sử dụng như sau để khi thay đổi phần tử của mảng thì không ảnh hưởng đến mảng kia

In [4]:
a_copy = a.copy()
a[0] = 5
print(a)
print(a_copy)

[5 2 3]
[1 2 3]


Tạo ndarray với hàm `zeros()`

In [5]:
a = np.zeros((2, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

Tạo ndarray với hàm `ones()`

In [6]:
a = np.ones((2, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

Tạo ndarray với hàm `full()`

In [7]:
b = np.full((2, 3), 9)
b

array([[9, 9, 9],
       [9, 9, 9]])

Tạo ma trận đơn vị

In [8]:
c = np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Dưới đây là một số hàm hữu ích để theo dõi shape, hữu ích cho việc gỡ lỗi và biết kích thước sẽ hữu ích khi tính toán 

**reshape**: cung cấp một hình dạng mới cho một mảng mà không thay đổi dữ liệu của nó

In [14]:
nums = np.arange(8)
print(nums)
print(nums.shape)

nums = nums.reshape((2, 4))
print("Reshape:\n", nums)

print(nums.shape)

[0 1 2 3 4 5 6 7]
(8,)
Reshape:
 [[0 1 2 3]
 [4 5 6 7]]
(2, 4)


Trong phương thức `reshape()`, ta có thể dùng tham số `-1` trong việc reshape với một dimension ta không biết mà numpy sẽ tự tìm ra dựa trên tất cả các dimension khác trong array size.

In [19]:
nums = nums.reshape((8, -1))
print('Reshape with -1:\n', nums, '\nshape:\n', nums.shape)

Reshape with -1:
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]] 
shape:
 (8, 1)


Cách chuyển về mảng 1 chiều

In [20]:
nums.reshape(-1)
nums.flatten()
nums.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

NumPy hỗ trợ một mô hình hướng đối tượng, sao cho ndarray có một số phương thức và thuộc tính, với các hàm tương tự như trong namespace Numpy ngoài cùng. Ví dụ, chúng ta có thể làm cả hai cách và cho kết quả như nhau

In [21]:
nums = np.arange(8)
print(nums.min())
print(np.min(nums))

print(np.reshape(nums, (4, 2)))
print(nums.reshape((4,2)))

print(np.mean(nums))
print(nums.mean())

0
0
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
3.5
3.5


#### **Datatypes**
Mỗi mảng Numpy là một lưới các phần tử cùng loại. Numpy cung cấp một tập hợp lớn các kiểu dữ liệu số mà bạn có thể sử dụng để xây dựng các mảng. Numpy cố gắng đoán một kiểu dữ liệu khi bạn tạo một mảng. Nhưng các hàm xây dựng các mảng thường cũng bao gồm một đối số tùy chọn để chỉ định rõ ràng kiểu dữ liệu. 

In [22]:
import numpy as np

x = np.array([1, 2])
print(x.dtype)

x = np.array([1.0, 2.0])
print(x.dtype)

x = np.array([1, 2], dtype=np.int64)
print(x.dtype)

int32
float64
int64


### **Array Operations/Math**
#### **Basic Math**
NumPy hỗ trợ rất nhiều các phép toán cơ bản như sau:

In [23]:
x = np.array([[1, 2],
              [3, 4]], dtype=np.float64)
y = np.array([[5, 6],
              [7, 8]], dtype=np.float64)

# Elementwise sum; cả hai cách đều ra kq như nhau
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))


[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


#### **Dot Product**
Chú ý $*$ là phép nhân toán tử, không phải phép nhân ma trận. Thay vào đó chúng ta sử dụng hàm **dot** để tính tích của 2 vector, nhân vector với ma trận, nhân ma trận với ma trận. **dot** có sẵn ở cả numpy như một hàm của numpy module hoặc là một **instance method** của đối tượng array. Ta có thể xem ví dụ

In [24]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(v, w))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))


219
219
[29 67]
219
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


#### **Across specific axes of the ndarray**
Có nhiều hàm hữu ích được tích hợp trong NumPy và thường chúng ta có thể thể hiện chúng qua các trục cụ thể của ndarray

In [27]:
x = np.array([
    [
        [8, 9],
        [10, 11],
        [12, 13]
    ],
    [
        [8, 9],
        [10, 11],
        [12, 13]
    ]
])

print(x.shape)

print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

(2, 3, 2)
126
[[16 18]
 [20 22]
 [24 26]]
[[30 33]
 [30 33]]


Chúng ta có thể tìm thấy các chỉ số (index) của các phần tử thỏa mãn một số điều kiện nào đó bằng cách sử dụng `np.where()`

In [32]:
nums = np.array([
    [1, 2, 7],
    [4, 5, 6]
])

x = np.array([
    [1, 2, 3],
    [-1, -2, -3]
])

print(np.where(nums > 5))
print(x[np.where(nums > 5)])

(array([0, 1], dtype=int64), array([2, 2], dtype=int64))
[ 3 -3]


Lưu ý khi bạn áp dụng các thao tác sẽ loại bỏ chiều cũ của nó ra khỏi hình dạng (shape). Điều này rất hữu ích để ghe nhớ khi bạn đang cố gắng tìm trục nào tương ứng với các gì. Ví dụ sau sử dụng hàm dim chỉ số chiều của mảng

In [33]:
x = np.array([[1, 2, 3], 
              [4, 5, 6]])

print('x ndim:', x.ndim) # sẽ in ra 2 vì x có 2 chiều
print((x.max(axis=0)).ndim) # trả ra mảng gồm các phần tử max theo cột có shape(3,0) 
                             # khi thêm ".ndim" sẽ trả ra là 1 vì mảng có 1 chiều.

# An array with rank 3
x = np.array([[[1, 2, 3], 
               [4, 5, 6]],
              [[10, 23, 33], 
               [43, 52, 16]]
             ])

print('x ndim:', x.ndim)               # Has shape (2, 2, 3)
print((x.max(axis=1)).ndim) # Taking the max over axis 1 has shape (2, 3)
print((x.max(axis=(1, 2))).ndim)       # Can take max over multiple axes; prints [6 52]


x ndim: 2
1
x ndim: 3
2
1


#### **Transposing**
Ngoài việc tính toán các hàm toán học bằng cách sử dụng các mảng, chúng ta thường cần phải định hình lại hoặc thao tác dữ liệu trong các mảng. Ví dụ đơn giản nhất của loại hoạt động này là chuyển vị (transposing) ma trận. Để hoán vị một ma trận, chỉ cần sử dụng thuộc tính **T** của một array object:

In [34]:
import numpy as np

x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

# Chú ý rằng chuyển vị 1 mảng có rank = 1 không thay đổi gì cả:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"


[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


#### **Vertical & Horizontal Stacking**
Tiếp theo, nếu bạn muốn nối hai mảng và không chỉ thêm chúng, bạn có thể thực hiện nó bằng cách xếp chồng dọc và xếp chống ngang

In [35]:
import numpy as np
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(np.vstack((x,y)))
print(np.hstack((x,y)))


[[1 2 3]
 [3 4 5]
 [1 2 3]
 [3 4 5]]
[[1 2 3 1 2 3]
 [3 4 5 3 4 5]]


#### **Array indexing**
Numpy cung cấp một số cách để truy xuất phần tử trong mảng

**Slicing**: Tương tự như list trong Python, numpy arrays cũng có thể được cắt (sliced). Vì các mảng có thể là đa chiều, bạn phải chỉ định một lát cho mỗi chiều của mảng. Ví dụ

In [36]:
# Tạo một numpy array có shape (3, 4) với giá trị như sau:
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
print('Original:\n', a)

# Can select an element as you would in a 2 dimensional Python list
print('Element (0, 0) (a[0][0]):\n', a[0][0])   # Prints 1
# or as follows
print('Element (0, 0) (a[0, 0]) :\n', a[0, 0])  # Prints 1

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
print('Sliced (a[:2, 1:3]):\n', a[:2, 1:3])

# Steps are also supported in indexing. The following reverses the first row:
print('Reversing the first row (a[0, ::-1]) :\n', a[0, ::-1]) # Prints [4 3 2 1]

# slice by the first dimension, works for n-dimensional array where n >= 1
print('slice the first row by the [...] operator: \n', a[0, ...])


Original:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Element (0, 0) (a[0][0]):
 1
Element (0, 0) (a[0, 0]) :
 1
Sliced (a[:2, 1:3]):
 [[2 3]
 [6 7]]
Reversing the first row (a[0, ::-1]) :
 [4 3 2 1]
slice the first row by the [...] operator: 
 [1 2 3 4]


Thông thường, thật hữu ích khi chọn hoặc sửa đổi một phần tử mỗi hàng của ma trận. Ví dụ sau sử dụng **fancy indexing**, trong đó chúng ta lập chỉ mục vào mảng của chúng tôi bằng cách sử dụng một mảng các chỉ số (giả sử một mảng các số nguyên hoặc booleans):

In [37]:
# Tạo một mảng mới
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])

print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Tạo một mảng chỉ số
b = np.array([0, 2, 0, 1])

# Chọn một phần tử từ mỗi hàng của a bằng cách sử dụng các chỉ số trong b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

# same as
for x, y in zip(np.arange(4), b):
    print(a[x, y])

c = a[0]
c[0] = 100
print(a)

# Đột biến một phần tử từ mỗi hàng của a bằng cách sử dụng các chỉ số trong b
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
1
6
7
11
[[100   2   3]
 [  4   5   6]
 [  7   8   9]
 [ 10  11  12]]
[[110   2   3]
 [  4   5  16]
 [ 17   8   9]
 [ 10  21  12]]


**Boolean array indexing**: Cho phép bạn chọn ra các phần tử tùy ý của một mảng, thường được sử dụng để chọn ra các phần tử thỏa mãn điều kiện nào đó. Ví dụ ta thay đổi giá trị các phần tử trong mảng lớn hơn MAX = 5 thành một số khác như 100

In [38]:
MAX = 5
nums = np.array([1, 4, 10, -1, 15, 0, 5])
print(nums > MAX)         # Prints [False, False, True, False, True, False, False]

nums[nums > MAX] = 100
print(nums)               # Prints [  1   4 100  -1 100   0   5]


[False False  True False  True False False]
[  1   4 100  -1 100   0   5]


Hoặc in ra các phần tử thỏa mãn điều kiện nào đó:

In [39]:
x = np.arange(8) 
print(x[x>3]) # Prints "[4 5 6 7]"


[4 5 6 7]


#### **Broadcasting**
Nhiều phép toán chúng ta đã xem xét ở trên là các mảng cùng rank. Tuy nhiên, nhiều lần chúng ta có thể có một mảng nhỏ hơn và sử dụng nhiều lần để cập nhật một mảng có kích thước lớn hơn. Ví dụ, hãy xem ví dụ dưới đây về việc dịch chuyển giá trị trung bình của mỗi cột từ các thành phần của cột tương ứng

In [40]:
x = np.array([[1, 2, 3],
              [3, 5, 7]])
print(x.shape)  # Prints (2, 3)

col_means = x.mean(axis=0)
print(col_means)          # Prints [2. 3.5 5.]
print(col_means.shape)    # Prints (3,)
                          # Has a smaller rank than x!

mean_shifted = x - col_means
print('\n', mean_shifted)
print(mean_shifted.shape)  # Prints (2, 3)


(2, 3)
[2.  3.5 5. ]
(3,)

 [[-1.  -1.5 -2. ]
 [ 1.   1.5  2. ]]
(2, 3)


**Broadcasting** 2 arrays với nhau tuân theo các quy luật sau:

1. Nếu các mảng không cùng rank, sẽ thêm vào shape của mảng **low rank** với 1 cho đến khi **shape** của cả 2 mảng có cùng **length**
2. Hai mảng được coi là tương thích về **dimension** nếu chúng có cùng size trong **dimension** hoặc 1 trong các mảng có size 1 trong **dimension** đó.
3. Các mảng có thể **broadcast** nếu chúng tương thích ở tất cả các chiều.
4. Sau khi **broadcasting**, mỗi mảng hoạt động như thể nó có **shape** bằng **maximum of shapes** của 2 mảng đầu vào.
5. Trong bất kỳ **dimension** nào trong đó một mảng có kích thước 1 và mảng khác có kích thước lớn hơn 1, mảng đầu tiên hoạt động như thể nó được sao chép dọc theo **dimension** đó.

Để cho dễ hiểu, thì khi thực hiện phép trừ cột ở trên, chúng ta có các mảng có shape (2,3) và (3,).

1. Các mảng này không có cùng thứ hạng, vì vậy chúng ta bổ sung 1 vào shape của mảng thấp rank hơn để tạo ra **shape** (1,3).
2. (2, 3) và (1, 3) tương thích (có cùng size trong dimension hoặc nếu một trong các mảng có size 1 trong dimension đó).
3. Có thể được **broadcast** cùng nhau!
4. Sau khi **broadcasting**, mỗi mảng hoạt động như thể nó có **shape** bằng (2, 3).
5. Mảng nhỏ hơn sẽ hoạt động như thể nó được sao chép dọc theo chiều 0. (theo cột )


In [41]:
x = np.array([[1, 2, 3],
              [3, 5, 7]])
print(x.shape)  # Prints (2, 3)

row_means = x.mean(axis=1)
print('row_means shape:', row_means.shape)
row_means = row_means.reshape(2,1)

mean_shifted = x - row_means
print(mean_shifted)
print(mean_shifted.shape)  # Prints (2, 3)


(2, 3)
row_means shape: (2,)
[[-1.  0.  1.]
 [-2.  0.  2.]]
(2, 3)


#### **View vs Copies (option)**
Không giống như **copy**, trong một **view** của một mảng, dữ liệu được chia sẻ giữa chế độ **view** và **array**. Đôi khi kết quả của chúng ta là bản sao của một mảng, nhưng lần khác chúng có thể là **views**. Hiểu khi nào chúng được tạo ra là một việc quan trọng để tránh các vấn đề bạn không thể lường trước được.

**Views** có thể tạo từ **slice** của một mảng, thay đổi dtype của cùng một vùng dữ liệu (sử dụng `arr.view(dtype)`, không phải kết quả của `arr.astype(dtype)`).

Ta sẽ xem qua các ví dụ sau để có thể hiểu rõ về view hơn.

In [42]:
import numpy as np
x = np.arange(5)
print('Original:\n', x)  # Prints [0 1 2 3 4]

# Modifying the view will modify the array
view = x[1:3]
view[1] = -1
print('Array After Modified View:\n', x)  # Prints [0 1 -1 3 4]


Original:
 [0 1 2 3 4]
Array After Modified View:
 [ 0  1 -1  3  4]


In [43]:
x = np.arange(5)
view = x[1:3]
view[1] = -1

# Modifying the array will modify the view
print('View Before Array Modification:\n', view)  # Prints [1 -1]
x[2] = 10
print('Array After Modifications:\n', x)          # Prints [0 1 10 3 4]
print('View After Array Modification:\n', view)   # Prints [1 10]


View Before Array Modification:
 [ 1 -1]
Array After Modifications:
 [ 0  1 10  3  4]
View After Array Modification:
 [ 1 10]


Tuy nhiên khi chúng ta sử dụng fancy indexing (được giới hiệu ở phần indexing bên trên) thì kết quả chắc chắn là một copy, không phải một view.

Ví dụ 1

In [44]:
x = np.arange(5)
print('Original:\n', x)  # Prints [0 1 2 3 4]

# Modifying the result of the selection due to fancy indexing
# will not modify the original array.
copy = x[[1, 2]]
copy[1] = -1
print('Copy:\n', copy) # Prints [1 -1]
print('Array After Modified Copy:\n', x)  # Prints [0 1 2 3 4]


Original:
 [0 1 2 3 4]
Copy:
 [ 1 -1]
Array After Modified Copy:
 [0 1 2 3 4]


Ví dụ 2

In [45]:
# Another example involving fancy indexing
x = np.arange(5)
print('Original:\n', x)  # Prints [0 1 2 3 4]

copy = x[x >= 2]
print('Copy:\n', copy) # Prints [2 3 4]
x[3] = 10
print('Modified Array:\n', x)  # Prints [0 1 2 10 4]
print('Copy After Modified Array:\n', copy)  # Prints [2 3 4]


Original:
 [0 1 2 3 4]
Copy:
 [2 3 4]
Modified Array:
 [ 0  1  2 10  4]
Copy After Modified Array:
 [2 3 4]
